# Generated by Django 5.1.5 on 2025-03-17 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('law', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('prah', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='FormModel',
        ),
    ]
