# Generated by Django 5.1.5 on 2025-03-17 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('law', '0002_services_delete_formmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='image',
            field=models.ImageField(blank=True, null=None, upload_to=''),
        ),
    ]
