# Generated by Django 5.1.5 on 2025-03-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('law', '0004_alter_services_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='image',
            field=models.ImageField(default=2, upload_to='images/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
