# Generated by Django 5.1.5 on 2025-03-18 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('law', '0006_sumdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sumdata',
            old_name='Reason_for_Contact',
            new_name='reason_for_contact',
        ),
        migrations.AlterField(
            model_name='sumdata',
            name='message',
            field=models.TextField(max_length=500),
        ),
    ]
