# Generated by Django 5.1.5 on 2025-03-20 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('law', '0007_rename_reason_for_contact_sumdata_reason_for_contact_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sumdata',
            old_name='reason_for_contact',
            new_name='subject',
        ),
    ]
